#![forbid(unsafe_code)]

use std::{
    env, fs, io,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{
    Fields, GenericArgument, Item, ItemStruct, Meta, PathArguments, Type, punctuated::Punctuated,
};

const GENERATED_HEADER: &str =
    "// @generated by `cargo run -p hubuum_reconcile -- update`; do not edit by hand.";
const SPECS: &[&str] = &[
    "class",
    "collection",
    "export_template",
    "group",
    "object",
    "service_account",
    "user",
];
type DynError = Box<dyn std::error::Error>;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Mode {
    Check,
    Update,
}

#[derive(Clone, Copy, Debug, Default)]
struct FieldOptions {
    read_only: bool,
    post_only: bool,
    optional: bool,
    post_optional: bool,
    as_id: bool,
    skip_patch: bool,
    skip_query: bool,
    default: bool,
    default_local: bool,
}

impl FieldOptions {
    fn parse(field: &syn::Field) -> syn::Result<Self> {
        let mut options = Self::default();
        for attr in &field.attrs {
            if !attr.path().is_ident("api") {
                continue;
            }
            let Meta::List(list) = &attr.meta else {
                return Err(syn::Error::new_spanned(
                    attr,
                    "expected `#[api(option, ...)]`",
                ));
            };
            let nested =
                list.parse_args_with(Punctuated::<Meta, syn::Token![,]>::parse_terminated)?;
            for meta in nested {
                let Meta::Path(path) = &meta else {
                    return Err(syn::Error::new_spanned(
                        meta,
                        "API field options must be identifiers",
                    ));
                };
                let Some(option) = path.get_ident() else {
                    return Err(syn::Error::new_spanned(
                        path,
                        "API field options must be unqualified identifiers",
                    ));
                };
                let option_name = option.to_string();
                let slot = match option_name.as_str() {
                    "read_only" => &mut options.read_only,
                    "post_only" => &mut options.post_only,
                    "optional" => &mut options.optional,
                    "post_optional" => &mut options.post_optional,
                    "as_id" => &mut options.as_id,
                    "skip_patch" => &mut options.skip_patch,
                    "skip_query" => &mut options.skip_query,
                    "default" => &mut options.default,
                    "default_local" => &mut options.default_local,
                    _ => {
                        return Err(syn::Error::new_spanned(
                            option,
                            format!("unknown API field option `{option_name}`"),
                        ));
                    }
                };
                if *slot {
                    return Err(syn::Error::new_spanned(
                        option,
                        format!("duplicate API field option `{option_name}`"),
                    ));
                }
                *slot = true;
            }
        }

        if options.read_only && options.post_only {
            return Err(syn::Error::new_spanned(
                field,
                "a field cannot be both `read_only` and `post_only`",
            ));
        }
        if options.post_only && (options.optional || options.post_optional) {
            return Err(syn::Error::new_spanned(
                field,
                "a `post_only` field cannot be optional",
            ));
        }
        if options.default && options.default_local {
            return Err(syn::Error::new_spanned(
                field,
                "a field cannot use both `default` and `default_local`",
            ));
        }
        Ok(options)
    }
}

struct ResourceField<'a> {
    syntax: &'a syn::Field,
    options: FieldOptions,
}

impl<'a> ResourceField<'a> {
    fn parse(field: &'a syn::Field) -> syn::Result<Self> {
        Ok(Self {
            syntax: field,
            options: FieldOptions::parse(field)?,
        })
    }

    fn ident(&self) -> &syn::Ident {
        self.syntax
            .ident
            .as_ref()
            .expect("ApiResource only supports named fields")
    }

    fn ty(&self) -> &Type {
        &self.syntax.ty
    }
}

#[derive(Default)]
struct GeneratedFields {
    resource: TokenStream,
    get: TokenStream,
    post: TokenStream,
    patch: TokenStream,
}

fn main() -> Result<(), DynError> {
    let mode = parse_mode(env::args().skip(1))?;
    let root = repository_root()?;
    let mut stale = Vec::new();
    let mut updated = 0;
    for name in SPECS {
        let spec_path = root
            .join("hubuum_reconcile/specs")
            .join(format!("{name}.rs"));
        let output_path = root
            .join("src/resources/generated")
            .join(format!("{name}.rs"));
        let generated = generate_file(&spec_path)?;
        let current = read_existing_output(&output_path)?;
        match mode {
            Mode::Check => {
                if current.as_deref() != Some(&generated) {
                    stale.push(output_path);
                }
            }
            Mode::Update => {
                if current.as_deref() == Some(&generated) {
                    continue;
                }
                let parent = output_path
                    .parent()
                    .ok_or("generated output has no parent")?;
                fs::create_dir_all(parent)?;
                fs::write(&output_path, generated)?;
                println!("updated {}", display_path(&root, &output_path));
                updated += 1;
            }
        }
    }

    if stale.is_empty() {
        match mode {
            Mode::Check => println!("generated resource code is current"),
            Mode::Update if updated == 0 => println!("generated resource code is already current"),
            Mode::Update => {}
        }
        Ok(())
    } else {
        for path in stale {
            eprintln!("stale: {}", display_path(&root, &path));
        }
        Err(
            "generated resource code is stale; run `cargo run -p hubuum_reconcile -- update`"
                .into(),
        )
    }
}

fn parse_mode(args: impl IntoIterator<Item = String>) -> Result<Mode, DynError> {
    let mut args = args.into_iter();
    let mode = match args.next().as_deref() {
        Some("check") => Mode::Check,
        Some("update") => Mode::Update,
        Some(other) => {
            return Err(format!("unknown mode `{other}`; use `check` or `update`").into());
        }
        None => return Err("missing mode; use `check` or `update`".into()),
    };
    if args.next().is_some() {
        return Err("expected exactly one mode: `check` or `update`".into());
    }
    Ok(mode)
}

fn read_existing_output(path: &Path) -> io::Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(contents) => Ok(Some(contents)),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error),
    }
}

fn repository_root() -> Result<PathBuf, DynError> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| "hubuum_reconcile must live directly below the repository root".into())
}

fn display_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
}

fn generate_file(path: &Path) -> Result<String, DynError> {
    let source = fs::read_to_string(path)?;
    let file = syn::parse_file(&source)?;
    let mut generated = TokenStream::new();
    for item in file.items {
        generated.extend(expand_item(item)?);
    }
    format_generated(generated)
}

fn format_generated(tokens: TokenStream) -> Result<String, DynError> {
    let input = format!("{GENERATED_HEADER}\n{tokens}\n");
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| io::Error::new(error.kind(), format!("failed to run rustfmt: {error}")))?;
    {
        use std::io::Write;
        child
            .stdin
            .take()
            .ok_or("failed to open rustfmt stdin")?
            .write_all(input.as_bytes())?;
    }
    let output = child.wait_with_output()?;
    if !output.status.success() {
        return Err(format!(
            "rustfmt failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )
        .into());
    }
    Ok(String::from_utf8(output.stdout)?)
}

fn expand_item(item: Item) -> syn::Result<TokenStream> {
    match item {
        Item::Struct(item) => expand_api_resource(item),
        other => Err(syn::Error::new_spanned(
            other,
            "ApiResource can only be generated from structs",
        )),
    }
}

fn pluralize(name: &syn::Ident) -> String {
    let name = name.to_string();
    match name.chars().last().expect("resource names are non-empty") {
        's' => format!("{name}es"),
        _ => format!("{name}s"),
    }
}

fn expand_api_resource(input: ItemStruct) -> syn::Result<TokenStream> {
    let source_name = &input.ident;
    let base_name = source_name.to_string();
    let Some(resource_name) = base_name.strip_suffix("Resource") else {
        return Err(syn::Error::new_spanned(
            source_name,
            "ApiResource requires a struct name ending in `Resource`",
        ));
    };
    if resource_name.is_empty() {
        return Err(syn::Error::new_spanned(
            source_name,
            "ApiResource requires a non-empty resource name before `Resource`",
        ));
    }

    let name = format_ident!("{resource_name}");
    let id_name = format_ident!("{}Id", name);
    let plural_name = format_ident!("{}", pluralize(&name));
    let async_checked_name = format_ident!("Async{}Create", name);
    let sync_checked_name = format_ident!("Sync{}Create", name);
    let (name_item_endpoint, name_param) = if name == "Class" {
        (
            quote!(Some(crate::endpoints::Endpoint::ClassesByName)),
            "class_name",
        )
    } else {
        (quote!(None), "name")
    };
    let name_field = match resource_name {
        "Group" => format_ident!("groupname"),
        _ => format_ident!("name"),
    };

    let fields = match &input.fields {
        Fields::Named(fields) => &fields.named,
        other => {
            return Err(syn::Error::new_spanned(
                other,
                "ApiResource requires a struct with named fields",
            ));
        }
    };
    let fields = fields
        .iter()
        .map(ResourceField::parse)
        .collect::<syn::Result<Vec<_>>>()?;
    let GeneratedFields {
        resource: main_fields,
        get: get_fields,
        post: post_fields,
        patch: patch_fields,
    } = process_fields(&fields, &id_name);

    let mut get_param_filters = TokenStream::new();
    let mut create_methods = TokenStream::new();
    let mut update_methods = TokenStream::new();
    let mut query_methods = TokenStream::new();
    let mut async_checked_create_methods = TokenStream::new();
    let mut sync_checked_create_methods = TokenStream::new();

    let required_create_fields = fields
        .iter()
        .filter(|field| {
            let options = field.options;
            (options.post_only || !options.read_only) && !options.optional && !options.post_optional
        })
        .collect::<Vec<_>>();
    let required_state_names = required_create_fields
        .iter()
        .map(|field| format_ident!("{}_SET", field.ident().to_string().to_uppercase()))
        .collect::<Vec<_>>();

    for field in &fields {
        let field_ident = field.ident();
        let field_name = field_ident.to_string();
        let field_ty = field.ty();
        let FieldOptions {
            read_only: is_read_only,
            post_only: is_post_only,
            optional: is_optional,
            post_optional: is_post_optional,
            as_id: is_as_id,
            skip_patch,
            skip_query,
            ..
        } = field.options;
        let post_patch_field_ident = if is_as_id {
            format_ident!("{}_id", field_name)
        } else {
            field_ident.clone()
        };
        let wrong_self_convention_allow =
            if field_name.starts_with("from_") || field_name.starts_with("to_") {
                quote!(#[allow(clippy::wrong_self_convention)])
            } else {
                quote!()
            };

        if !is_post_only && !skip_query {
            get_param_filters.extend(quote! {
                if let Some(value) = params.#post_patch_field_ident {
                    queries.push(crate::types::QueryFilter {
                        key: stringify!(#post_patch_field_ident).to_string(),
                        value: value.to_string(),
                        operator: crate::types::FilterOperator::Equals { is_negated: false },
                    });
                }
            });
            let field_wrapper = query_field_wrapper(field_ty, is_as_id);
            query_methods.extend(quote! {
                #wrong_self_convention_allow
                pub fn #post_patch_field_ident(self) -> #field_wrapper {
                    <#field_wrapper>::new(self, stringify!(#post_patch_field_ident))
                }
            });
        }

        if is_post_only || !is_read_only {
            let create_field_ty = if is_post_only {
                quote!(#field_ty)
            } else if is_as_id {
                if is_optional || is_post_optional {
                    quote!(Option<<#field_ty as crate::resources::ApiResource>::Id>)
                } else {
                    quote!(<#field_ty as crate::resources::ApiResource>::Id)
                }
            } else if is_optional || is_post_optional {
                quote!(Option<#field_ty>)
            } else {
                quote!(#field_ty)
            };
            let (arg_ty, assign_expr) = fluent_arg_and_assign(&create_field_ty);
            create_methods.extend(quote! {
                pub fn #post_patch_field_ident(self, value: #arg_ty) -> Self {
                    self.edit_params(move |params| {
                        params.#post_patch_field_ident = #assign_expr;
                    })
                }
            });

            let checked_return_states = required_create_fields
                .iter()
                .zip(required_state_names.iter())
                .map(|(required, state)| {
                    if required.ident() == field.ident() {
                        quote!(true)
                    } else {
                        quote!(#state)
                    }
                })
                .collect::<Vec<_>>();
            async_checked_create_methods.extend(quote! {
                #wrong_self_convention_allow
                pub fn #post_patch_field_ident(self, value: #arg_ty) -> #async_checked_name<
                    #(#checked_return_states),*
                > {
                    #async_checked_name {
                        inner: self.inner.#post_patch_field_ident(value),
                    }
                }
            });
            sync_checked_create_methods.extend(quote! {
                #wrong_self_convention_allow
                pub fn #post_patch_field_ident(self, value: #arg_ty) -> #sync_checked_name<
                    #(#checked_return_states),*
                > {
                    #sync_checked_name {
                        inner: self.inner.#post_patch_field_ident(value),
                    }
                }
            });
        }

        if !is_post_only && !is_read_only && !skip_patch {
            let patch_field_ty = if is_as_id {
                if is_optional {
                    quote!(Option<<#field_ty as crate::resources::ApiResource>::Id>)
                } else {
                    quote!(<#field_ty as crate::resources::ApiResource>::Id)
                }
            } else {
                quote!(Option<#field_ty>)
            };
            let (arg_ty, assign_expr) = fluent_arg_and_assign(&patch_field_ty);
            update_methods.extend(quote! {
                pub fn #post_patch_field_ident(self, value: #arg_ty) -> Self {
                    self.edit_params(move |params| {
                        params.#post_patch_field_ident = #assign_expr;
                    })
                }
            });
        }
    }

    let get_name = format_ident!("{}Get", name);
    let post_name = format_ident!("{}Post", name);
    let patch_name = format_ident!("{}Patch", name);
    let endpoint = format_ident!("{}", plural_name);
    let item_endpoint = format_ident!("{}ById", plural_name);
    let id_param = id_param_name(&name.to_string());
    let state_definitions = required_state_names
        .iter()
        .map(|state| quote!(const #state: bool))
        .collect::<Vec<_>>();
    let state_arguments = required_state_names.iter().collect::<Vec<_>>();
    let initial_states = required_state_names
        .iter()
        .map(|_| quote!(false))
        .collect::<Vec<_>>();
    let complete_states = required_state_names
        .iter()
        .map(|_| quote!(true))
        .collect::<Vec<_>>();
    let display_field_options = &[
        format_ident!("name"),
        format_ident!("user"),
        format_ident!("username"),
        format_ident!("id"),
    ];
    let display_field = display_field_options
        .iter()
        .find(|field| fields.iter().any(|item| item.ident() == *field))
        .ok_or_else(|| {
            syn::Error::new_spanned(
                &input.ident,
                "ApiResource requires a `name`, `user`, `username`, or `id` field for Display",
            )
        })?;

    Ok(quote! {
        #[derive(Default, Debug, serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash)]
        #[serde(transparent)]
        pub struct #id_name(i32);

        impl #id_name {
            pub fn new(value: i32) -> Self { Self(value) }
            pub fn get(self) -> i32 { self.0 }
        }

        impl std::fmt::Display for #id_name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl std::str::FromStr for #id_name {
            type Err = <i32 as std::str::FromStr>::Err;
            fn from_str(value: &str) -> Result<Self, Self::Err> {
                value.parse::<i32>().map(Self)
            }
        }

        impl From<i32> for #id_name {
            fn from(value: i32) -> Self { Self(value) }
        }

        impl From<&#id_name> for #id_name {
            fn from(value: &#id_name) -> Self { *value }
        }

        impl From<#id_name> for i32 {
            fn from(value: #id_name) -> Self { value.0 }
        }

        impl PartialEq<i32> for #id_name {
            fn eq(&self, other: &i32) -> bool { self.0 == *other }
        }

        impl PartialEq<#id_name> for i32 {
            fn eq(&self, other: &#id_name) -> bool { *self == other.0 }
        }

        impl crate::resources::ResourceId for #id_name {
            fn new(value: i32) -> Self { Self(value) }
            fn get(self) -> i32 { self.0 }
        }

        #[derive(Default, Debug, serde::Serialize, serde::Deserialize, Clone, PartialEq)]
        #[non_exhaustive]
        pub struct #name { #main_fields }

        impl crate::client::GetID for #name {
            fn id(&self) -> Self::Id { self.id }
        }

        #[derive(Default, Debug, serde::Serialize, serde::Deserialize, Clone, PartialEq)]
        pub struct #get_name { #get_fields }

        #[derive(Default, serde::Serialize, serde::Deserialize, Clone, PartialEq)]
        pub struct #post_name { #post_fields }

        #[derive(Default, serde::Serialize, serde::Deserialize, Clone, PartialEq)]
        pub struct #patch_name { #patch_fields }

        impl std::fmt::Display for #name {
            fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                write!(f, "{}", self.#display_field)
            }
        }

        impl crate::resources::sealed::Sealed for #name {}

        impl crate::resources::ApiResource for #name {
            type Id = #id_name;
            type GetParams = #get_name;
            type GetOutput = #name;
            type PostParams = #post_name;
            type PostOutput = #name;
            type PatchParams = #patch_name;
            type PatchOutput = #name;
            type DeleteParams = ();
            type DeleteOutput = ();

            const NAME_FIELD: &'static str = stringify!(#name_field);
            const COLLECTION_ENDPOINT: crate::endpoints::Endpoint = crate::endpoints::Endpoint::#endpoint;
            const ITEM_ENDPOINT: Option<crate::endpoints::Endpoint> = Some(crate::endpoints::Endpoint::#item_endpoint);
            const ID_PARAM: &'static str = #id_param;
            const NAME_ITEM_ENDPOINT: Option<crate::endpoints::Endpoint> = #name_item_endpoint;
            const NAME_PARAM: &'static str = #name_param;

            fn endpoint(&self) -> crate::endpoints::Endpoint { Self::COLLECTION_ENDPOINT }

            fn build_params(filters: Vec<(String, crate::types::FilterOperator, String)>) -> Vec<crate::types::QueryFilter> {
                let mut queries = vec![];
                for (key, operator, value) in filters {
                    queries.push(crate::types::QueryFilter { key, value, operator });
                }
                queries
            }

            fn filters_from_get(params: Self::GetParams) -> Vec<crate::types::QueryFilter> {
                let mut queries = vec![];
                #get_param_filters
                queries
            }
        }

        #[cfg(feature = "blocking")]
        impl crate::client::sync::CreateOp<#name> { #create_methods }

        #[cfg(feature = "async")]
        impl crate::client::r#async::CreateOp<#name> { #create_methods }

        #[cfg(feature = "async")]
        pub struct #async_checked_name<#(#state_definitions),*> {
            inner: crate::client::r#async::CreateOp<#name>,
        }

        #[cfg(feature = "async")]
        impl<#(const #state_arguments: bool),*> #async_checked_name<#(#state_arguments),*> {
            #async_checked_create_methods
        }

        #[cfg(feature = "async")]
        impl #async_checked_name<#(#complete_states),*> {
            pub async fn send(self) -> Result<#name, crate::ApiError> { self.inner.send().await }
        }

        #[cfg(feature = "async")]
        impl crate::client::r#async::Resource<#name> {
            #[allow(deprecated)]
            pub fn create_checked(&self) -> #async_checked_name<#(#initial_states),*> {
                #async_checked_name { inner: self.create() }
            }
        }

        #[cfg(feature = "blocking")]
        pub struct #sync_checked_name<#(#state_definitions),*> {
            inner: crate::client::sync::CreateOp<#name>,
        }

        #[cfg(feature = "blocking")]
        impl<#(const #state_arguments: bool),*> #sync_checked_name<#(#state_arguments),*> {
            #sync_checked_create_methods
        }

        #[cfg(feature = "blocking")]
        impl #sync_checked_name<#(#complete_states),*> {
            pub fn send(self) -> Result<#name, crate::ApiError> { self.inner.send() }
        }

        #[cfg(feature = "blocking")]
        impl crate::client::sync::Resource<#name> {
            #[allow(deprecated)]
            pub fn create_checked(&self) -> #sync_checked_name<#(#initial_states),*> {
                #sync_checked_name { inner: self.create() }
            }
        }

        #[cfg(feature = "blocking")]
        impl crate::client::sync::UpdateOp<#name> { #update_methods }

        #[cfg(feature = "async")]
        impl crate::client::r#async::UpdateOp<#name> { #update_methods }

        #[cfg(feature = "blocking")]
        impl crate::client::sync::QueryOp<#name> { #query_methods }

        #[cfg(feature = "async")]
        impl crate::client::r#async::QueryOp<#name> { #query_methods }

        #[cfg(feature = "blocking")]
        impl crate::client::sync::Resource<#name> { #query_methods }

        #[cfg(feature = "async")]
        impl crate::client::r#async::Resource<#name> { #query_methods }
    })
}

fn option_inner_type(ty: &Type) -> Option<&Type> {
    let Type::Path(type_path) = ty else {
        return None;
    };
    let segment = type_path.path.segments.last()?;
    if segment.ident != "Option" {
        return None;
    }
    let PathArguments::AngleBracketed(args) = &segment.arguments else {
        return None;
    };
    let Some(GenericArgument::Type(inner)) = args.args.first() else {
        return None;
    };
    Some(inner)
}

fn type_name_is(ty: &Type, expected: &str) -> bool {
    let ty = option_inner_type(ty).unwrap_or(ty);
    let Type::Path(type_path) = ty else {
        return false;
    };
    type_path
        .path
        .segments
        .last()
        .is_some_and(|segment| segment.ident == expected)
}

fn is_string_type(ty: &Type) -> bool {
    type_name_is(ty, "String")
}

fn is_bool_type(ty: &Type) -> bool {
    type_name_is(ty, "bool")
}

fn is_json_value_type(ty: &Type) -> bool {
    type_name_is(ty, "Value")
}

fn is_numeric_or_datetime_type(ty: &Type) -> bool {
    let ty = option_inner_type(ty).unwrap_or(ty);
    let Type::Path(type_path) = ty else {
        return false;
    };
    let Some(segment) = type_path.path.segments.last() else {
        return false;
    };
    matches!(
        segment.ident.to_string().as_str(),
        "i8" | "i16"
            | "i32"
            | "i64"
            | "i128"
            | "isize"
            | "u8"
            | "u16"
            | "u32"
            | "u64"
            | "u128"
            | "usize"
            | "f32"
            | "f64"
            | "HubuumDateTime"
            | "DateTime"
            | "NaiveDateTime"
    )
}

fn is_id_type(ty: &Type) -> bool {
    let ty = option_inner_type(ty).unwrap_or(ty);
    let Type::Path(type_path) = ty else {
        return false;
    };
    type_path
        .path
        .segments
        .last()
        .is_some_and(|segment| segment.ident.to_string().ends_with("Id"))
}

fn query_value_type(field_ty: &Type, is_as_id: bool) -> TokenStream {
    if is_as_id {
        quote!(<#field_ty as crate::resources::ApiResource>::Id)
    } else {
        let ty = option_inner_type(field_ty).unwrap_or(field_ty);
        quote!(#ty)
    }
}

fn query_field_wrapper(field_ty: &Type, is_as_id: bool) -> TokenStream {
    let value_ty = query_value_type(field_ty, is_as_id);
    if is_as_id || is_numeric_or_datetime_type(field_ty) || is_id_type(field_ty) {
        quote!(crate::client::QueryNumericField<Self, #value_ty>)
    } else if is_string_type(field_ty) {
        quote!(crate::client::QueryTextField<Self>)
    } else if is_bool_type(field_ty) {
        quote!(crate::client::QueryBoolField<Self>)
    } else if is_json_value_type(field_ty) {
        quote!(crate::client::QueryJsonField<Self>)
    } else {
        quote!(crate::client::QueryValueField<Self, #value_ty>)
    }
}

fn id_param_name(name: &str) -> &'static str {
    match name {
        "User" => "user_id",
        "Group" => "group_id",
        "Class" => "class_id",
        "Collection" => "collection_id",
        "Object" => "object_id",
        "ExportTemplate" => "template_id",
        "ServiceAccount" => "service_account_id",
        "ClassRelation" | "ObjectRelation" => "relation_id",
        _ => "id",
    }
}

fn fluent_arg_and_assign(field_ty: &TokenStream) -> (TokenStream, TokenStream) {
    let parsed_ty: Type = syn::parse2(field_ty.clone()).expect("generated field type should parse");
    if let Some(inner) = option_inner_type(&parsed_ty) {
        if is_string_type(inner) {
            (quote!(impl Into<String>), quote!(Some(value.into())))
        } else if is_id_type(inner) {
            (quote!(impl Into<#inner>), quote!(Some(value.into())))
        } else {
            (quote!(#inner), quote!(Some(value)))
        }
    } else if is_string_type(&parsed_ty) {
        (quote!(impl Into<String>), quote!(value.into()))
    } else if is_id_type(&parsed_ty) {
        (quote!(impl Into<#parsed_ty>), quote!(value.into()))
    } else {
        (quote!(#parsed_ty), quote!(value))
    }
}

fn process_fields(fields: &[ResourceField<'_>], id_name: &syn::Ident) -> GeneratedFields {
    let mut generated = GeneratedFields::default();

    for field in fields {
        let name = field.ident();
        let field_name = name.to_string();
        let ty = field.ty();
        let FieldOptions {
            read_only: is_read_only,
            post_only: is_post_only,
            optional: is_optional,
            post_optional: is_post_optional,
            as_id: is_as_id,
            skip_patch,
            skip_query,
            default,
            default_local,
        } = field.options;
        let serde_default = if default_local {
            quote!(#[serde(default = "crate::types::default_local_identity_value")])
        } else if default {
            quote!(#[serde(default)])
        } else {
            quote!()
        };
        let id_field_name = if is_as_id {
            format!("{field_name}_id")
        } else {
            field_name.clone()
        };
        let id_field_ident = syn::Ident::new(&id_field_name, proc_macro2::Span::call_site());

        if !is_post_only {
            let main_field_ty = if field_name == "id" {
                quote!(#id_name)
            } else if is_optional {
                quote!(Option<#ty>)
            } else {
                quote!(#ty)
            };
            generated.resource.extend(quote! {
                #serde_default
                pub #name: #main_field_ty,
            });
            if !skip_query {
                let get_type = if is_as_id {
                    quote!(Option<<#ty as crate::resources::ApiResource>::Id>)
                } else {
                    quote!(Option<#ty>)
                };
                generated
                    .get
                    .extend(quote!(pub #id_field_ident: #get_type,));
            }
        }

        if is_post_only {
            generated.post.extend(quote!(pub #id_field_ident: #ty,));
        } else if !is_read_only {
            if is_as_id {
                let id_type = if is_optional || is_post_optional {
                    quote!(Option<<#ty as crate::resources::ApiResource>::Id>)
                } else {
                    quote!(<#ty as crate::resources::ApiResource>::Id)
                };
                if !skip_patch {
                    generated
                        .patch
                        .extend(quote!(pub #id_field_ident: #id_type,));
                }
                if is_post_optional {
                    generated.post.extend(quote! {
                        #[serde(skip_serializing_if = "Option::is_none")]
                        pub #id_field_ident: #id_type,
                    });
                } else {
                    generated
                        .post
                        .extend(quote!(pub #id_field_ident: #id_type,));
                }
            } else {
                if !skip_patch {
                    generated
                        .patch
                        .extend(quote!(pub #id_field_ident: Option<#ty>,));
                }
                let post_type = if is_optional || is_post_optional {
                    quote!(Option<#ty>)
                } else {
                    quote!(#ty)
                };
                if is_post_optional {
                    generated.post.extend(quote! {
                        #[serde(skip_serializing_if = "Option::is_none")]
                        pub #id_field_ident: #post_type,
                    });
                } else {
                    generated
                        .post
                        .extend(quote!(pub #id_field_ident: #post_type,));
                }
            }
        }
    }
    generated
}

#[cfg(test)]
mod tests {
    use super::{Mode, expand_item, parse_mode};
    use syn::parse_quote;

    #[test]
    fn parses_exactly_one_supported_mode() {
        assert_eq!(parse_mode(["check".to_owned()]).unwrap(), Mode::Check);
        assert_eq!(parse_mode(["update".to_owned()]).unwrap(), Mode::Update);

        let missing = parse_mode([]).unwrap_err();
        assert!(missing.to_string().contains("missing mode"));

        let unknown = parse_mode(["generate".to_owned()]).unwrap_err();
        assert!(unknown.to_string().contains("unknown mode `generate`"));

        let extra = parse_mode(["check".to_owned(), "extra".to_owned()]).unwrap_err();
        assert!(extra.to_string().contains("exactly one mode"));
    }

    #[test]
    fn rejects_resource_without_suffix() {
        let error = expand_item(parse_quote!(
            struct Widget {
                id: i32,
            }
        ))
        .unwrap_err();
        assert!(error.to_string().contains("ending in `Resource`"));
    }

    #[test]
    fn rejects_empty_resource_name() {
        let error = expand_item(parse_quote!(
            struct Resource {
                id: i32,
            }
        ))
        .unwrap_err();
        assert!(error.to_string().contains("non-empty resource name"));
    }

    #[test]
    fn rejects_non_struct_item() {
        let error = expand_item(parse_quote!(
            enum WidgetResource {
                First,
            }
        ))
        .unwrap_err();
        assert!(error.to_string().contains("generated from structs"));
    }

    #[test]
    fn rejects_unnamed_fields() {
        let error = expand_item(parse_quote!(
            struct WidgetResource(i32);
        ))
        .unwrap_err();
        assert!(error.to_string().contains("named fields"));
    }

    #[test]
    fn rejects_missing_display_field() {
        let error = expand_item(parse_quote!(
            struct WidgetResource {
                value: String,
            }
        ))
        .unwrap_err();
        assert!(error.to_string().contains("field for Display"));
    }

    #[test]
    fn rejects_unknown_field_option() {
        let error = expand_item(parse_quote!(
            struct WidgetResource {
                id: i32,
                #[api(unknown)]
                name: String,
            }
        ))
        .unwrap_err();
        assert!(error.to_string().contains("unknown API field option"));
    }

    #[test]
    fn rejects_duplicate_field_option() {
        let error = expand_item(parse_quote!(
            struct WidgetResource {
                id: i32,
                #[api(optional, optional)]
                name: String,
            }
        ))
        .unwrap_err();
        assert!(error.to_string().contains("duplicate API field option"));
    }

    #[test]
    fn rejects_incompatible_field_options() {
        let read_and_post = expand_item(parse_quote!(
            struct WidgetResource {
                id: i32,
                #[api(read_only, post_only)]
                name: String,
            }
        ))
        .unwrap_err();
        assert!(
            read_and_post
                .to_string()
                .contains("both `read_only` and `post_only`")
        );

        let post_and_optional = expand_item(parse_quote!(
            struct WidgetResource {
                id: i32,
                #[api(post_only, optional)]
                name: String,
            }
        ))
        .unwrap_err();
        assert!(
            post_and_optional
                .to_string()
                .contains("`post_only` field cannot be optional")
        );

        let conflicting_defaults = expand_item(parse_quote!(
            struct WidgetResource {
                id: i32,
                #[api(default, default_local)]
                name: String,
            }
        ))
        .unwrap_err();
        assert!(
            conflicting_defaults
                .to_string()
                .contains("both `default` and `default_local`")
        );
    }
}
